# Generated by Django 3.1.7 on 2021-06-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='')),
                ('cover_photo', models.FileField(blank=True, upload_to='')),
                ('username', models.CharField(max_length=3000, unique=True)),
                ('bio', models.CharField(blank=True, max_length=4000)),
                ('location', models.CharField(blank=True, max_length=4000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
